name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
          opam-repositories: |
            rocq-released: https://rocq-prover.org/opam/released
            default: https://github.com/ocaml/opam-repository.git
          dune-cache: true
      - name: Pin Rocq
        run: |
          opam pin add --dev-repo rocq-runtime
          opam pin add --dev-repo rocq-core
          opam pin add --dev-repo coq-core
          opam pin add --dev-repo rocq-stdlib
          opam pin add --dev-repo coq-stdlib
      - name: Pin Menhir
        run: |
          opam pin add menhirCST git+https://git.sr.ht/~henrytill/menhir#depend-on-coq-core
          opam pin add menhirLib git+https://git.sr.ht/~henrytill/menhir#depend-on-coq-core
          opam pin add menhirSdk git+https://git.sr.ht/~henrytill/menhir#depend-on-coq-core
          opam pin add menhir git+https://git.sr.ht/~henrytill/menhir#depend-on-coq-core
          opam pin add coq-menhirlib git+https://git.sr.ht/~henrytill/menhir#depend-on-coq-core
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
  linux-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix build -L --accept-flake-config
